### ISSUE TITLE
[FEAT] json 파일 정리 및 hint 추가

### ISSUE THREAD

**Issue by seoin0110** [multi-sensor/MultiSensoryEnhancementProgram#13]
## Background
- 이미지 파일들과 관련된 정보를 json data 형태로 map에 저장하여 사용합니다.

## Todo
- [x] json data 형식 결정
- [x] app_values.dart에 json data 저장하고, 하드코딩된 부분 대체하기 (crm_info, crm_img_slide)
- [x] crm_img_slide 이미지 확대할 수 있게 수정
- [x] crm_img_slide indicator를 숫자로 표현, 선택되지 않은 버튼 색 좀 더 진하게 수정 gray200 -> gray500
- [x] crm_img_slide 마지막에 완성 이미지 추가하기
- [x] crm_img_slide에서 hint버튼 추가 (guideBar widget으로 따로 빼둠)
