### ISSUE TITLE
[FEAT] 모든 파일 색상 수정

### ISSUE THREAD

**Issue by alimhanhan** [multi-sensor/MultiSensoryEnhancementProgram#28]
## Background
- 전체 파일 색상 수정

## Todo
- [x] 주황/빨강 계열은 maincolor으로 변경
- [x] 연한 노랑 계열은 sub1color으로 변경
- [x] 모든 흰색은 sub2color으로 변경
