### ISSUE TITLE
[FEAT] 24. 01. 12 회의 디자인 관련 피드백 사항 반영

### ISSUE THREAD

**Issue by alimhanhan** [multi-sensor/MultiSensoryEnhancementProgram#37]
## Background
- 24.01.12 회의 디자인 관련 피드백 사항 반영

## Todo
- [x] 맨 위에 바 검은 줄 없애기
- [x] 상단 바 중앙부분은 비워두기
- [x] 배경은 전달받은 이미지로 대체(모든 페이지 대상) → 이미지 색상따서, AppBar 색상은 흰색으로
- [x]  카테고리 아이콘 하얀색, 글자 검정색
- [x]  레벨 카테고리 글자 키우기
- [x]  메뉴 카테고리 팝업창 테두리 radius 추가
- [x]  가이드 버튼 우측 상단으로 이동 + X 아이콘버튼으로 대체
- [x]  카테고리 창 글자 크기 키우기
