### ISSUE TITLE
[FEAT] 레벨 팝업 창(Dialog) 변경

### ISSUE THREAD

**Issue by alimhanhan** [multi-sensor/MultiSensoryEnhancementProgram#54]
## Background
- 레벨 팝업 창(Dialog) 변경

## Todo
- [x] crm_img_button.dart에 팝업 버튼 색상 지정
- [x] crm_colors.dart 에 색상 6개 추가
- [x] 팝업창 중앙 상단에 카테고리명 추가
