### ISSUE TITLE
[FEAT] 새로운 디자인 반영

### ISSUE THREAD

**Issue by seoin0110** [multi-sensor/MultiSensoryEnhancementProgram#65]
## Background
- 리뉴얼된 디자인을 반영합니다.

## Todo
- [x] 프리뷰 페이지 추가
- [x] contents 페이지 디자인 수정
- [x]  app values 구조 리펙토링
